name: Run bot

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "user_interface.py"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4.0.0

      - name: Prepare config
        run: sed -i "s/TokenTimeIsBackBuddyss/${{ secrets.LICHESS_KEY }}/g" config.yml

      - name: Make Stockfish executable
        run: chmod +x ./engines/stockfish

      - name: Fast install expect
        run: sudo apt-get update -qq && sudo apt-get install -yq --no-install-recommends expect

      - name: Run bot with matchmaking, wait, then stop
        run: |
          expect <<'EOF'
          log_user 1
          spawn python -u user_interface.py
          expect {
            -re ".*" { exp_continue }
            timeout { }
          }
          send "matchmaking\r"
          sleep $((5 * 60 * 60 + 50 * 60))
          send "stop\r"
          expect eof
          EOF
