name: Run Both Bots

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "user_interface.py"
  schedule:
    - cron: '0 */2 * * *' # runs every 2 hours

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  lichess-bot:
    name: Run AlPhAbEtACeta
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Python Dependency Installation
        uses: py-actions/py-dependency-install@v4.0.0
      - name: Injection For my Repo
        run: sed -i "s/TokenTimeIsBackBuddyss/${{ secrets.LICHESS_KEY }}/g" config.yml
      - name: Stockfish
        run: chmod +x ./engines/stockfish
      - name: Running bot
        run: python -u user_interface.py --matchmaking

  bullet-bot:
    name: Run LeoMessi-bot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Python Dependency Installation
        uses: py-actions/py-dependency-install@v4.0.0
      - name: Injection For my Repo
        run: sed -i "s/TokenTimeIsBackBuddyss/${{ secrets.BULLET_KEY }}/g" config.yml
      - name: Stockfish
        run: chmod +x ./engines/stockfish
      - name: Running bot
        run: python -u user_interface.py --matchmaking
  chess-bot:
    name: Run RookSquadUnited
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Python Dependency Installation
        uses: py-actions/py-dependency-install@v4.0.0
      - name: Injection For my Repo
        run: sed -i "s/TokenTimeIsBackBuddyss/${{ secrets.CHESS_KEY }}/g" config.yml
      - name: Stockfish
        run: chmod +x ./engines/stockfish
      - name: Running bot
        run: python -u user_interface.py --matchmaking      
