# This is a basic workflow to help you get started with Actions

name: Run bot

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "user_interface.py"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Python Dependency Installation
        uses: py-actions/py-dependency-install@v4.0.0

      - name: Injection For my Repo
        run: sed -i "s/TokenTimeIsBackBuddyss/${{ secrets.LICHESS_KEY }}/g" config.yml

      - name: Stockfish
        run: chmod +x ./engines/stockfish

      - name: Fast expect install
        run: |
          sudo apt-get update -qq
          sudo apt-get install -yq --no-install-recommends expect

      - name: Run bot
        run: |
          set -x
          python -u user_interface.py <<EOF
          matchmaking
          EOF
          sleep $((5 * 60 * 60 + 50 * 60))
          python -u user_interface.py <<EOF
          stop
          EOF
