# This is a basic workflow to help you get started with Actions

name: Run bot

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "user_interface.py"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Python Dependency Installation
        uses: py-actions/py-dependency-install@v4.0.0

      - name: Injection For my Repo
        run: sed -i "s/TokenTimeIsBackBuddyss/${{ secrets.LICHESS_KEY }}/g" config.yml

      - name: Stockfish
        run: |
          chmod +x ./engines/stockfish

      - name: Install expect
        run: sudo apt-get update && sudo apt-get install -y expect

      - name: running bot (test version, low sleep)
        run: |
          expect <<EOF
          log_user 1
          spawn python -u user_interface.py
          send "matchmaking\r"
          sleep 5
          send "quit\r"
          expect eof
          EOF
